### ISSUE TITLE
Window Rect

### ISSUE THREAD

**Issue by LordJZ** [D-Key/whosh#1]
Hi D-Key,

First or all, sorry for contacting you here, as I do not have a Habrahabr account, neither have you specified your email at your github page.

Your implementation is wonderful, yet incomplete. I'm a WPF developer myself, and the reason I still do not use VS2012-like and Office 2013-like window styles in WPF, is because windows like yours (or my own implementation) yield wrong GetWindowRect results. I find this a serious issue.

The rectangle returned is the rectangle of the 'true' window, that is, including the shadow and the transparent part. When you see it, it looks very ugly. Possibly the best way to see it is:
1. Sleep the rendering thread (UI thread) for a while. Let's say, for 30 seconds.
2. Now, quickly switch to your window, click it here and there until DWM considers it freezed and renders the standard border itself.
Another simple way to 'see' the window rectangle, is using an app like AltDrag.

I have open-sourced my own window style a few minutes ago: https://gist.github.com/4076728
This is an advanced window, that fully emulates standard window behavior (at least on Windows 8) -- even better than VS2012 window itself! My implementation is based on MahApps.Metro window.
Please also keep in mind that my window's XAML template is not generic there -- I do not have a generic template (yet).

Now, if we do cooperate, we may solve even more issues and make a perfect generic window style. If you agree with me, could you please send me an email (visible on my github page), or contact me in any other way that works for you?
I do have most of IM protocols, feel free to use any one that suits best for you. We can still talk here of course.

Thanks!
-LordJZ

**Comment by D-Key** [comment]
Responded in e-mail.
